application: musinformatics
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: off
- admin_redirect: off
- deferred: off
- remote_api: off

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: numpy
  version: "latest"


handlers:
- url: /favicon.ico
  static_files: application/static/img/favicon.ico
  upload: application/static/img/favicon.ico

- url: /robots.txt
  static_files: application/static/robots.txt
  upload: application/static/robots.txt

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application

- url: /static
  static_dir: application/static

- url: /semantic/dist
  static_dir: application/semantic/dist

- url: .*
  script: run.application.app
